### ISSUE TITLE
csv files

### ISSUE THREAD

**Issue by theroonba** [lexibank/asjp#10]
A few notes about the csv files (forms, languages, etc.)

As the first 2 characters of the csv file are "ID", Excel thinks the file is an SYLK file rather than a CSV file (changing the "ID" to something else fixes this issue).  The file still opens, but Excel gives an error while opening it.

In forms:
In the GRAPHEMES column (which I believe is formatted for lingpy in Python):

~ is the marker for combining the 2 previous symbols - this works fine, and merges the 2 previous symbols (should the tilde remain after this merger?) 
**example**: sisx~li becomes [^ s i xs~ l i $] - shouldn't this be [^ s i xs l i $]?

$ is the marker for combining the 3 previous symbols - this doesn't seem to work - the 3 symbols are not combined in the grapheme form (**it is also used for the marker for the end of the grapheme,** which may be confusing, as it seems the end of the grapheme is in the middle of the word).
**example**: wsk$aw becomes [^ w s k $ a w $] - shouldn't this be [^ wsk a w $]?

" is the marker for an ejective - this works properly BUT wouldn't it be better to use another symbol? Quotation marks are notoriously difficult to work with in programming (and in Excel), especially as strings are usually contained within a set of quotation marks.

The asterisk is the nasal marker - this is also difficult to work with in Excel (* is a reserved symbol, which makes searching for it within text difficult)

**Comment by LinguList** [comment]
Thanks. The csv dormat follows the standard specs. If excel causes problems, they need to adjust their software. In fact, you can tell excel what file you want to load, I am sure there is a workaround from within excel.

Graphemes is not for lingpy. It reflects our segmentation procedure. You point to errors there, with start and end symbols. They should be fixed by us.

As the symbols in Graphemes reflect Asjp, we cannot replace them by different symbols. The column more interesting for you to search is Segments, providing the results of the conversion to some reduced bzt standart IPA. Graphemes just helps us to debug, and the errors you found are a good example, why that is important.
