### ISSUE TITLE
Add orthography profile

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/asjp#2]
@LinguList -- don't you have one somewhere?

**Comment by tresoldi** [comment]
I have one, but I understood we would not give segments here?

**Comment by LinguList** [comment]
It is just important to check if there's a flag for ASJP in the BIPA evaluation, since this is not BIPA now, but ASJP, right?

As for an orthoprofile: lingpy has a simple segmentation algorithm that also works, but a profile is probably better.

And if we manage to segment the data, we can show that we do more than JUST rendering data, and having ASJP in feature-form may in fact come in handy.

**Comment by SimonGreenhill** [comment]
done in #4
